name: shared_services
description: Shared services and models for Coupona app (Supabase client, models, parsers)
version: 0.0.1
environment:
  sdk: ">=3.8.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.7
  easy_localization: ^3.0.5
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.2
  latlong2: ^0.9.0

flutter:
  uses-material-design: true
